CREATE TABLE hasil_papi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nip VARCHAR(20) NOT NULL,
    
    -- 10 Dimensi Roles (Dihitung dari A Horizontal / B Diagonal tertentu)
    G TINYINT DEFAULT 0, L TINYINT DEFAULT 0, I TINYINT DEFAULT 0, 
    T TINYINT DEFAULT 0, V TINYINT DEFAULT 0, S TINYINT DEFAULT 0, 
    R TINYINT DEFAULT 0, D TINYINT DEFAULT 0, C TINYINT DEFAULT 0, E TINYINT DEFAULT 0,
    
    -- 10 Dimensi Needs (Dihitung dari B Diagonal)
    N TINYINT DEFAULT 0, A TINYINT DEFAULT 0, P TINYINT DEFAULT 0, 
    X TINYINT DEFAULT 0, B TINYINT DEFAULT 0, O TINYINT DEFAULT 0, 
    K TINYINT DEFAULT 0, F TINYINT DEFAULT 0, W TINYINT DEFAULT 0, Z TINYINT DEFAULT 0,
    
    tanggal_tes TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (nip) REFERENCES users(nip) ON DELETE CASCADE
);